# Get your key from: https://platform.openai.com/api-keys
OPENAI_API_KEY: "YOUR OPENAI KEY HERE"

# Get your key from: https://aistudio.google.com/app/apikey
GOOGLE_API_KEY: "sample"

OLLAMA_MODEL: "gemma3:latest"
